name: (M) Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag next major/minor release. Use 1.x.x scheme. Leave default iterate to auto tag the next patch version.'
        required: true
        default: 'iterate'
permissions:
  contents: write
jobs:
  release:
    name: Tag code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: UCBoulder/oitid_reusable_actions/.github/workflows/releases.yml@main
        env:
          set_version: ${{ github.event.inputs.version }}
          email: "buffalor@colorado.edu"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_user: ${{ github.actor }}
          repo: ${{ github.repository }}
